component_depth: 6
languages:
- name: csharp
  production:
    include:
      - .*/Main/.*\.cs
      - .*/Director/.*\.cs
      - .*/Enforcer/.*\.cs
      - .*/Fido_Support/.*\.cs
      - .*/Notification/.*\.cs
      - .*/Properties/.*\.cs



